### ISSUE TITLE
Fix Travis failures.

### ISSUE THREAD

**Issue by garnertb** [FireCARES/firecares#97]
```
0.56s$ python manage.py test
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/contrib/auth/models.py", line 41, in <module>
    class Permission(models.Model):
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/db/models/base.py", line 139, in __new__
    new_class.add_to_class('_meta', Options(meta, **kwargs))
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/db/models/base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/db/models/options.py", line 250, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/db/utils.py", line 240, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 8, in <module>
    from .features import DatabaseFeatures
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/features.py", line 1, in <module>
    from django.contrib.gis.db.backends.base.features import BaseSpatialFeatures
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/contrib/gis/db/backends/base/features.py", line 3, in <module>
    from django.contrib.gis.db.models import aggregates
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/contrib/gis/db/models/__init__.py", line 7, in <module>
    from django.contrib.gis.geos import HAS_GEOS
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/contrib/gis/geos/__init__.py", line 15, in <module>
    from .geometry import GEOSGeometry, wkt_regex, hex_regex
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/contrib/gis/geos/geometry.py", line 10, in <module>
    from django.contrib.gis.gdal.error import SRSException
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/contrib/gis/gdal/__init__.py", line 47, in <module>
    from django.contrib.gis.gdal.driver import Driver  # NOQA
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import lgdal
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/site-packages/django/contrib/gis/gdal/libgdal.py", line 48, in <module>
    lgdal = CDLL(lib_path)
  File "/home/travis/miniconda2/envs/condaenv/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/travis/miniconda2/envs/condaenv/bin/../lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /usr/lib/libblas.so.3gf)
```

**Comment by MBARIMike** [comment]
I just got the same error on my project. Can this be fixed by setting an environment variable in .travis.yml? I had similar errors with HDF and NetCDF that were fixed with these settings:

    - export HDF5_DIR=/home/travis/miniconda2/
    - export NETCDF4_DIR=/home/travis/miniconda2/

**Comment by garnertb** [comment]
@MBARIMike, thanks for the help.  I had to set the `LD_PRELOAD` env variable to get it working again.

```
env:
  global:
    - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3 matlab
```
